### ISSUE TITLE
Remove redunant closing tag 

### ISSUE THREAD

**Issue by KarelWintersky** [1234ru/websun#1]
`?>`
at end of php file

**Comment by 1234ru** [comment]
Actually, this tag is necessary. Why do you call it redundant? Are you sure?

**Comment by KarelWintersky** [comment]
В общем, я поискал, где он уже не требуется:
https://stackoverflow.com/a/4465825
http://php.net/manual/ru/language.basic-syntax.phptags.php

**Comment by 1234ru** [comment]
Ок, принято.
