### ISSUE TITLE
"Импорт" переменных в шаблон

### ISSUE THREAD

**Issue by KarelWintersky** [1234ru/websun#2]
Код 
[Полный код тут](https://github.com/KarelWintersky/kwLME.LiveMap/blob/a08bf6783ff838511db4006d853c93eeea519354/controller.edit.php)
```
$edit_templates = [];
$edit_templates_index = 1;

// тут мы как-то заполняем эту переменную описанием шаблонов  
if ($json->templates) {
            foreach ($json->templates as $template_record) {
                $template = [
                    'title'     =>  $template_record->title ?? "#{$edit_templates_index}",
                    'desc'      =>  $template_record->description ?? "#{$edit_templates_index}",
                    'url'       =>  "/storage/{$edit_map_alias}/edit_templates/" . $template_record->url
                ];

                $edit_templates[] = $template;
                $edit_templates_index++;
            }

            $edit_templates_styles = $json->edit_templates->styles ?? "";
            if ($edit_templates_styles)
                $edit_templates_styles = "/storage/{$edit_map_alias}/edit_templates/" . $edit_templates_styles;
        }

// а теперь задаем переменные для импорта в шаблон
        $template_data = array(
            'html_callback'     =>  "/map/{$edit_map_alias}",
            'region_title'      =>  ($region_data['is_present'] == 1) ? htmlspecialchars($region_data['title']) : '',
            'region_text'       =>  $region_data['content'],
            'is_logged_user'    =>  $userinfo['email'],
            'is_logged_user_ip' =>  $userinfo['ip'],

            'edit_templates_styles' => $edit_templates_styles,
            // и много других полей, но 'edit_templates'   =>  $edit_templates, среди них НЕТ
        );
// и ниже 

$template_file = 'edit.region.page.html';
$template_path = PATH_TEMPLATES . 'edit.region/';
echo websun_parse_template_path($template_data, $template_file, $template_path);
```

Код шаблона: 
```
...
templates           : [ {?*$edit_templates*}{%*$edit_templates*}
                {
                    "title"         :   "{*$edit_templates:title*}",
                    "description"   :   "{*$edit_templates:desc*}",
                    "url"           :   "{*$edit_templates:url*}"
                }, {*$edit_templates*%}{*$edit_templates*?}
            ],
            template_popup_height   : 400,
            template_popup_width    : 800,
{?*edit_templates_styles*}
            content_css         : "{*edit_templates_styles*}"
{*edit_templates_styles*?}
...
```

Я ожидал, что в результате "рендера" никаких упоминаний об этой секции **не будет**. Каково же было моё удивление, когда я увидел вполне себе валидный код:

```
templates           : [
                {
                    "title"         :   "Подробный шаблон",
                    "description"   :   "Шаблон с филдсетами",
                    "url"           :   "/storage/spring.confederation/edit_templates/tinymce.fieldsets.html"
                },
                {
                    "title"         :   "Краткий шаблон",
                    "description"   :   "Шаблон plain/text",
                    "url"           :   "/storage/spring.confederation/edit_templates/tinymce.plaintext.html"
                },
            ],
            template_popup_height   : 400,
            template_popup_width    : 800,

            content_css         : "/storage/spring.confederation/edit_templates/template-styles.css"
...
```

То есть переменная-массив в шаблон каким-то образом импортировалась из глобальной области видимости. 

А вот единичная переменная без прямого объявления в шаблон не импортируется

Что это - **бага** или **фича**?

**Comment by 1234ru** [comment]
Если имя переменной начинается с `$`, то она берется из глобальной области видимости. Фича :) Причем старая, с самой первой опубликованной версии. Вы, наверное, проглядели этот абзац в статье (хотя там не очень наглядный пример - можно глобальные и суперглобальные перепутать):

> Можно также обращаться к переменным глобальной области видимости, в т.ч. суперглобальным массивам. Для этого перед именем переменной нужно поставить знак доллара. Например, подстановка в шаблон переменной `$_GET['foo']` выглядит так: `{*$_GET.foo*}`.

Вот у вас написано `{*$edit_templates*}` - это из глобальной. А дальше - `{*edit_templates_styles*}`, это - не из глобальной.

**Comment by 1234ru** [comment]
А вообще я вам рекомендую массивы готовить полностью в PHP и пользоваться json_encode():


```

$WEBSUN_ALLOWED_CALLBACKS[] = 'json_encode';
...
echo websun_parse_template_path(...);
```
А в шаблоне:

`{* @json_encode(*json*) *}`

(хотя имя ключа стоит поменять с `json `на что-то другое, т.к. json - это всегда строка, а у вас там массив)

**Comment by KarelWintersky** [comment]
> А  вообще я вам рекомендую массивы готовить полностью в PHP и пользоваться json_encode():

Там json загружается из файла конфига (это костыль, должно быть из БД на самом деле) и некоторым образом обрабатывается...  ну, это видно.

> Если имя переменной начинается с $, то она берется из глобальной области видимости.

Внезапно, там действительно с долларом. Мда, я ослеп. А фича... интересная.
