### ISSUE TITLE
Проверка непустого поля в цикле

### ISSUE THREAD

**Issue by KarelWintersky** [1234ru/websun#3]
```
{%*region_revisions*}
        <li>
{*region_revisions:edit_name*} 
edited `{*region_revisions:title*}` 
at {*region_revisions:edit_date*} 
from IP {*region_revisions:ipv4*} 

{?*region_revisions:edit_comment*}
<small>{*region_revisions:edit_comment*}</small>
{*region_revisions:edit_name*?}
;
       </li>
        {*region_revisions*%}
```

Структура заполняется вот таким запросом:
```
SELECT
  table_data.id_region AS id_region,
  table_data.edit_date AS edit_date,
  table_users.username AS edit_name,
  INET_NTOA(`edit_ipv4`) AS ipv4,
  title,
  table_data.edit_comment AS edit_comment
FROM
  {$table_data} AS table_data,
  {$table_users} AS table_users
WHERE
    alias_map = :alias_map
AND id_region = :id_region
AND table_data.edit_whois = table_users.id
ORDER BY edit_date ;
```

Результат рендера **всей** страницы пустой абсолютно, в логе никаких ошибок не возникает.

Если исключить блок
```
{?*region_revisions:edit_comment*}
<small>{*region_revisions:edit_comment*}</small>
{*region_revisions:edit_name*?}
```
все ок.

Ожидаемое поведение: если `$template['region_revisions'][N]['edit_comment']` непустое - выводится блок.

**Comment by 1234ru** [comment]
Потому что у вашего if в шаблоне в открывающей конструкции одна переменная стоит, а в закрывающей другая. Сравните `{?*region_revisions:edit_comment*}` и `{*region_revisions:edit_name*?}`. 

А вообще бросайте вы уже старый длинный синтаксис if'ов. Для того короткий и придуман, чтоб не было таких неудобств. 
```
{?*region_revisions:edit_comment*}
<small>{*region_revisions:edit_comment*}</small>
{?}

```
Разве не лучше?

И про отрицательную часть - `{?!} ... {?}` - тоже не забывайте.

**Comment by KarelWintersky** [comment]
Лучше конечно.
Но, боюсь, я запутаться смогу. Если я уж такие очевидные ошибки допускаю - то длинный синткаксис должен (!) помочь не запутаться.

**Comment by 1234ru** [comment]
А вы возьмите правило делать отступы как в коде, и не запутаетесь:
```
{?*region_revisions:edit_comment*}
	<small>{*region_revisions:edit_comment*}</small>
{?}
```
