### ISSUE TITLE
Remove extra empty lines

### ISSUE THREAD

**Issue by KarelWintersky** [1234ru/websun#5]
Используется вот такой шаблон:
```
    "regions": {
    {%*regions*}
        "{*regions:id*}" : {
            "id"        : "{*regions:id*}",
            "type"      : "{*regions:type*}",
            "coords"    : {*regions:js*},
{?*regions:fillColor*}            "fillColor" : "{*regions:fillColor*}", {?}
{?*regions:fillOpacity*}            "fillOpacity": {*regions:fillOpacity*}, {?}
{?*regions:fillRule*}            "fillRule": "{*regions:fillRule*}", {?}
{?*regions:title*}            "title": "{*regions:title*}", {?}
{?*regions:desc*}            "desc": "{*regions:desc*}", {?}
{?*regions:radius*}            "radius": {*regions:radius*},{?}
        },
    {%}
    }
```

[ссылка на шаблон](https://github.com/KarelWintersky/kwLME.LiveMap/blob/4de74a707933b3db3288fae779081e5be1f20509/templates/view.map/viewmap.jslayout-struct.tpl)

Рендер шаблона порождает файл с пустыми строками:
```
  "regions": {
    
        "path4468" : {
            "id"        : "path4468",
            "type"      : "polygon",
            "coords"    : [ [766.78,1057.32], [768.16,1048.33], [761.53,1042.1], [770.51,1040.62], [774.39,1032.39], [778.56,1040.48], [787.59,1041.62], [781.19,1048.09], [782.89,1057.03], [774.76,1052.94] ],



            "title": "Сириус", 


        },
```
[пример файла](http://livemap.wintersky.ru/js/map/spring.confederation.js)

То есть пустые строки вставляются аккурат туда, где в шаблоне задано правило
```
{?*regions:fillColor*}            "fillColor" : "{*regions:fillColor*}", {?}
```
и ему подобные, по которому ничего в шаблон не вставляется кроме `\n` (присутствующего в конце строки). 

С одной стороны это логично, а с другой требует дополнительной постобработки срендеренного шаблона (я это делаю с помощью регулярки `$content = preg_replace('/^\h*\v+/m', '', $content);` )

Можно как-нибудь изменить это поведение? Опция в шаблонизатор?

**Comment by KarelWintersky** [comment]
Поправка: если просто пойти браузером на пример файла - он все покажет, но нифига не выровняет по строчкам. Поэтому лучше идти через исходный код отсюда: http://livemap.wintersky.ru/map/spring.confederation

**Comment by 1234ru** [comment]
> Можно как-нибудь изменить это поведение? Опция в шаблонизатор?

К сожалению, нет, т.к. шаблонизатору сложно объяснить, где нужно удалять пустые строки, а где - нет. В общем-то, это и не его задача.
Только вот зачем Вам в данном случае избавляться от пустых строк? Чем они Вам мешают?

**Comment by KarelWintersky** [comment]
> Только вот зачем Вам в данном случае избавляться от пустых строк? Чем они Вам мешают?

Некрасиво ;-)

**Comment by 1234ru** [comment]
Ох... Ну, некрасиво либо тут, либо в шаблонизаторе. Поверьте, второе хуже :)

**Comment by KarelWintersky** [comment]
Верю.
