### ISSUE TITLE
Неопределеный вызов в parse_vars_templates_functions()

### ISSUE THREAD

**Issue by KarelWintersky** [1234ru/websun#6]
В коде `parse_vars_templates_functions()`
есть одинокая строчка [Call;](https://github.com/1234ru/websun/blob/master/websun.php#L736)

```
$call; // Сюда запишем некоторые параметры того, что будем вызывать
				       // Вообще не круто использоват наряду с $callback (см. ниже),
					   // но лучше ничего не придумалось.
```
IDE мне подчеркивает это как ошибку.
Это какая-то хитрая магия, которой я не понимаю?

**Comment by 1234ru** [comment]
Нет, это просто способ записать что-то о переменной. Если мешается в IDE, можно убрать.

**Comment by KarelWintersky** [comment]
+++
